### ISSUE TITLE
User Interview with Maggie

### ISSUE THREAD

**Issue by sandikbarr** [PRX/metrics.prx.org#10]
@farksi and @sandikbarr will interview marketing about how they might use metrics to inform decisions

**Comment by sandikbarr** [comment]
So many meetings scheduled this week. I slack chatted Maggie to ask her a couple of questions. She says it's almost impossible right now to tell whether a marketing campaign (tweet, FB post, article in a news publication, blog post, paid ads on Google or FB) has driven a download spike. Having metrics available on that same day (currently we're not getting metrics until the day after) would be helpful in determining correlation but she's not 100% sure how to draw conclusions on conversions from these campaigns. Playback data will be more timely and accurate than download data, so more helpful. She can't say for sure that 15 minute or hourly interval breakdown will help her determine these correlations and will probably stick to mostly looking at daily download data.

**Comment by pkarman** [comment]
Is it possible to attach a unique campaign id of some flavor to the download URL for various distribution channels?

**Comment by sandikbarr** [comment]
Hmmm... It seems more likely that we could do something like campaign ids with the URL parameters in the embeddable player.
