### ISSUE TITLE
Downloads Geolocation charts and data

### ISSUE THREAD

**Issue by sandikbarr** [PRX/metrics.prx.org#100]
Three dimensions of data:
* ISO 3166 country
* ISO 3166-2 subdivisions (e.g. state/province/other, almost all countries have regions)
* Metro regions (DMA in the US)

1 show or 1 episode at a time
Map view by default (toggle to chart? What kind?)
Possibly sorting in table view? Table UI component will have configurable per-column sorting.
Possible frontend filter to exclude a country or region, improve the dynamic spread of the gradient shading/coloring.

**Comment by pkarman** [comment]
@sandikbarr could you take a first pass at scoring the associated tickets for this epic?

**Comment by sandikbarr** [comment]
all issues in epic closed or ice boxed, closing
