### ISSUE TITLE
Downloads User Agent charts and data

### ISSUE THREAD

**Issue by sandikbarr** [PRX/metrics.prx.org#101]
Three dimensions of data:
* Normalized UA string (app/browser)
* Device Type (form factor)
* Operating System

1 show or 1 episode at at time
Ok to keep table data sparse (2 columns), as it gives 1:1 parity between mobile and desktop
Possibly sorting in table view? Table UI component will have configurable per-column sorting.
Default graph should not be single line.

**Comment by pkarman** [comment]
@sandikbarr could you take a first pass at scoring the associated tickets for this epic?

**Comment by cavis** [comment]
Deploy'd!
