### ISSUE TITLE
Podcast Profile section

### ISSUE THREAD

**Issue by sandikbarr** [PRX/metrics.prx.org#106]
A podcast profile section is shown in the upper right. This ticket includes the basic info. Performance info will be added with #144
 * [x] A rounded (border radius 50%, similar to the navuser image) series image
 * [x] The Series title on a single line with overflow ellipsis
 * [x] The Most Recent Episode title on a single line with overflow ellipsis
 * [x] Most recent episode title is link to multi-line chart with only the single episode charted
![screen shot 2017-11-29 at 1 56 39 pm](https://user-images.githubusercontent.com/2250413/33396113-315778ec-d50d-11e7-830c-ffd35413ddf6.png)

**Comment by sandikbarr** [comment]
why is the podcast profile image a circle when podcast images are square by design? (at least I assumed that's what the blue dot is)

**Comment by pkarman** [comment]
Is this really high? I think we should bump this and #144 unless there's a functional gap that users will notice.
