### ISSUE TITLE
remove gutters?

### ISSUE THREAD

**Issue by sandikbarr** [PRX/metrics.prx.org#111]
Are the gutters removed in the new page layout or is the max width just larger? Is there a target size in mind? I realize it's not pixel perfect, but when comparing the items in the navbar, the new design doesn't actually look any wider than our current 1200px max width

**Comment by kookster** [comment]
@farski this looks to be the only open issue for the epic, can you weigh in?

**Comment by farski** [comment]
The width max for content/nav in beta (and I believe Publish) was 1000pt, so filling 1200 with content is a change. Or I've missed cases where we've done that in the past.

**Comment by farski** [comment]
I'm not sure that answers your questions @sandikbarr, let me know if not

**Comment by sandikbarr** [comment]
Beta and Publish and Metrics (from the styleguide) all have max-width: 1200px on the body. So this is not a change, closing...
