### ISSUE TITLE
Chart colors

### ISSUE THREAD

**Issue by sandikbarr** [PRX/metrics.prx.org#113]
What colors should be used for the different chart types?
* Single line
* Multi-line (up to 10 episodes can be shown)
* Stacked area (up to 10 episodes)

While the multi-line and stacked area are charting basically the same thing, the visualizations have different intent, so using the same colors may not make the most sense. Currently the stacked area uses tints of #205060, a darker shade of our standard blue #368aa2.

**Comment by pkarman** [comment]
@farski this issue is blocking #108 so I am assigning to you with a low estimate and high priority.

**Comment by pkarman** [comment]
Since it's blocking a ticket in Xeva I have put it in the same milestone but if for some reason this can't be accomplished in this sprint, we'll need to push both tickets to the next sprint.

**Comment by farski** [comment]
Seems to me like there's enough larger functional work in #108 that as long as we can pretty easily adjust the color palette next sprint, final colors for this shouldn't be a blocker for that ticket. I think we have to expect that we'll refine these colors as we have time to live with them and the various functions that determine how they're being used. These 10 are fine placeholders for the time being

#a6cee3
#1f78b4
#b2df8a
#33a02c
#fb9a99
#e31a1c
#fdbf6f
#ff7f00
#cab2d6
#6a3d9a
