### ISSUE TITLE
See data for previously published episodes

### ISSUE THREAD

**Issue by kookster** [PRX/metrics.prx.org#115]
Some podcasts, like TAL, will un-publish older episodes, keeping only a handful in the feed.
We need a way to be able see data for these previously published episodes.
This will require CMS changes: https://github.com/PRX/cms.prx.org/issues/376

**Comment by sandikbarr** [comment]
Castle has data on episodes that have been removed from feeder. If episode titles are duplicated, the first part of the guid is added to the charted episode title.
