### ISSUE TITLE
summary table/expandable report

### ISSUE THREAD

**Issue by sandikbarr** [PRX/metrics.prx.org#119]
* [x] A summary view with Total during the period, average, and all time downloads will be the default table view
* [x] The user can select to expand out the table to also show the report breakdown containing each of the individual data points.
* [x] A Google Analytics event will be tied to this expand button so we can see how often users are looking at the reports

**Comment by gcampo88** [comment]
note to self: per slack discussion, the average should be the average per the selected interval. e.g. if the user has selected Daily, we should show Daily Average (as in mockup). 


design q: is this the design to work off of? @farski / @sandikbarr ? https://drive.google.com/file/d/18uV471p6ATZb0kuxmJj7YgR5ABZReL9L/view

**Comment by sandikbarr** [comment]
@gcampo88 yup, that's the design but it's not showing the expandable report because I convinced @kookster and @farski we shouldn't take away the full report until there is a reports replacement, so that part of the design with the expandable button is mostly a vague idea in my head. With the ability to expand to the full report, I feel like the summary table doesn't need to take up the full width of the content area.

Implementation wise, I think we could put the summary stuff in the first "sticky" table and make the report the second scrolling table.
