### ISSUE TITLE
loading is wonky

### ISSUE THREAD

**Issue by sandikbarr** [PRX/metrics.prx.org#128]
This is a collection of feedback about loading but no specific solutions just yet. We had said the requirement was to not show partially loaded views, but some of this feedback and some of the current behavior don't really go along with that.
* The chart shows up before the menu and table show up
* Episodes come in and load into a jumpy table after the spinner goes away
  * seemed like it had gotten the list of episodes from CMS, and was sending off the 10-ish requests to Castle
  * then those table-rows show up as Castle returns
  * i was thinking we could pre-render the list of episode-titles immediately, without waiting for Castle
  * guess what i find most disjointing is when Castle returns out-of-order, and your episode list jumps around a bit
* Loading indicator seems a bit heavy handed (removing pretty much everything and showing the spinner feels funky)

**Comment by pkarman** [comment]
These are user facing and contribute to initial impression, so I'd like to keep in beta. Making this high so it gets some attention.

My 2c is to show the mask till everything is loaded. Even if that takes an extra second or two, it prevents the jumping effect.

**Comment by sandikbarr** [comment]
Agreed. I'd like to work on this next, either before or after the range-then-bucket changes.
