### ISSUE TITLE
Design sidebar for responsive layout

### ISSUE THREAD

**Issue by pkarman** [PRX/metrics.prx.org#130]
The sidebar design in https://drive.google.com/file/d/18uV471p6ATZb0kuxmJj7YgR5ABZReL9L/view
needs some thought about how it behaves on a mobile device.

Follow on to #28

**Comment by farski** [comment]
My inclination is to handle this roughly the same way it gets handled in Beta. The difference being that we'd be moving the sidebar nav and the header nav into the drawer, but that seems fine. The show selector could be done as an vertical accordion or popup. 

![image](https://user-images.githubusercontent.com/3483/35282900-c68664e0-0024-11e8-8656-7ffee216d9fb.png)

**Comment by pkarman** [comment]
I'm having a hard time imagining how that screen snap translates to the metrics UI. Can you mock something up, even a wireframe, to show how the metrics app would work on the smaller screen size?
