### ISSUE TITLE
replace series dropdown with index page

### ISSUE THREAD

**Issue by sandikbarr** [PRX/metrics.prx.org#135]
We will remove the dropdown in the navbar, and top level navigation to different podcasts will be done via an index page that will eventually grow into our dashboard.

**Comment by kookster** [comment]
We're not sure how much this will actually get used, so maybe build something simple but still useful.

Also need to consider what the menu looks like to link to this index page from on the page for a series (i.e. a link to "Series" in the nav, kinda like the nav links in publish?)

**Comment by kookster** [comment]
we'll need to decide if this is pressing for the current sprint - and when we can get an index page designed and built before we can change/remove the dropdown

**Comment by pkarman** [comment]
Let's bump this out of beta. @sandikbarr has recently added a scrolling nav dropdown to select from. We can revisit this after beta.
