### ISSUE TITLE
metrics summary

### ISSUE THREAD

**Issue by sandikbarr** [PRX/metrics.prx.org#136]
A summary of the metrics shown in the chart will appear below the menu bar and above the chart with total downloads and average per day.

@farski when showing different chart types, what is in this summary when multiple episode are shown? Is it still based on the podcast metrics when on the multi line and stacked episode charts?

**Comment by farski** [comment]
Yeah I think for now let's keep that as totals for the selected range. The idea of having numbers the reflect the selection is interesting, though, so it's something to flag for later

**Comment by sandikbarr** [comment]
@farski My question was more along the lines of when showing the episodes multi-line chart, what is shown in that summary area? Still the podcast total and daily average? How about the stacked episode + podcast chart? -podcast total and daily average? What about when the interval is hourly, weekly or monthly, is that a hourly, weekly, or monthly average?

**Comment by farski** [comment]
@sandikbarr Ah, gotcha. My thought has been that the summary would always reflect all data for the selected range

**Comment by sandikbarr** [comment]
The average adjusts with the interval (same as the averages in the summary table) but the total downloads is always at the podcast level even when the podcast is not in the chart.

3. @sandi.barr re: https://github.com/PRX/metrics.prx.org/issues/136 it sounded like there was some limitation with getting the total for a range?
GitHub
metrics summary · Issue #136 · PRX/metrics.prx.org
A summary of the metrics shown in the chart will appear below the menu bar and above the chart with total downloads and average per day. @farski when showing different chart types, what is in this ...
 


Sandi Barr [2:32 PM] 
We should have the totals for a range available. We'll be doing that math for the summary table.

Chris Kalafarski [2:33 PM] 
oh ok. so we’re good with this ticket?


[2:33] 
that’s all I meant my “reflect all data”


Sandi Barr [2:33 PM] 
My question is I just dont know what to show there when it is not the single line podcast chart. Is it the same?


Chris Kalafarski [2:34 PM] 
yeah; I’d have it always show the total for the range, regardless of how it’s broken down by interval, series, etc

Sandi Barr [2:34 PM] 
the total downloads on the podcast as a whole when it's showing episodes in the chart?


Chris Kalafarski [2:35 PM] 
yep. that summary is intended to be a summary of the range


Sandi Barr [2:36 PM] 
Next question, we decided that when the interval was hourly, weekly, or monthly, the summary table would show hourly, weekly, monthly averages instead of daily average. Same here?


Chris Kalafarski [2:38 PM] 
uploaded and commented on this image: image.png
  1 Comment

I think the 22 days stays as days (at least for now as we work through that other ticket) but avg/day could change to reflect the currently selected interval
