### ISSUE TITLE
move default filter to routing effects

### ISSUE THREAD

**Issue by sandikbarr** [PRX/metrics.prx.org#137]
When first loading the default filter is determined for date range and interval. This currently happens in the downloads component but should be incorporated with filterFromRoute$ in the routing.effects.

**Comment by sandikbarr** [comment]
This will also fix a bug where if the page is refresh on demographics or traffic sources routes the sidebar nav doesn't have any links because Ngrx doesn't have the series id.

**Comment by pkarman** [comment]
@sandikbarr is this bug still present? I didn't notice it during your demo.

**Comment by sandikbarr** [comment]
It is, but I didn't refresh on Demographics or Traffic Sources routes. I did however get it fixed with my router state serializer, the PR I'm currently working on. So yes, we can bump this. (Even though I'm very close to making this change in the refactor.)
