### ISSUE TITLE
getChartData selector

### ISSUE THREAD

**Issue by sandikbarr** [PRX/metrics.prx.org#141]
A chart data selector would use the router state against the metrics stores to build the chart data including the podcast and/or episode data when charted as well as order the episode data according to total when the chart type is stacked.

**Comment by pkarman** [comment]
can we bump this out since not user-facing?

**Comment by sandikbarr** [comment]
This is a larger refactor that will follow the RouterStateSerializer but it's not necessary that it happen directly after the RouterStateSerializer, so yes, this one makes sense to bump. It's gonna simplify the chart component a lot and will make maintenance and enhancements so much easier to handle, so it is high value and we should keep at least medium priority.
