### ISSUE TITLE
getMetricsSummaryData selector

### ISSUE THREAD

**Issue by sandikbarr** [PRX/metrics.prx.org#142]
a metrics summary data selector would combine routing state with podcast, episode, and metrics state to return data to be displayed in the summary table

**Comment by sandikbarr** [comment]
Needs to be refactored to use RouteStateSerializer

**Comment by pkarman** [comment]
can we bump this out since it is not user-facing?

**Comment by sandikbarr** [comment]
I created the selectors when I added the summary info, but I'm gonna need to refactor it with this RouterStateSerializer PR, so it will be fully completed today.

**Comment by sandikbarr** [comment]
This was already done
