### ISSUE TITLE
Podcast Profile performance info

### ISSUE THREAD

**Issue by sandikbarr** [PRX/metrics.prx.org#144]
In the podcast profile section, show
 * [ ] Total downloads on the podcast for the current day (UTC)
    * [ ] and an indicator whether that number is up or down from prior period
 * [ ] Total downloads on the podcast over the last seven days (UTC)
    * [ ] and an indicator whether that number is up or down from prior period
 * [ ] Total downloads on the most recent episode for the current day (UTC)
 * [ ] Total all time downloads on the most recent episode

**Comment by pkarman** [comment]
given that this is new functionality, I'd like to bump out of beta.

**Comment by cavis** [comment]
Depends on PRX/castle.prx.org#52.  (This data should be pulled from the all-time / "show" endpoints in Castle).

**Comment by cavis** [comment]
Data is now in prod.  Just need to start pulling it in the Effect, and loading the "all time downloads" podcast/episode into this component.
