### ISSUE TITLE
Odd dropdown animation

### ISSUE THREAD

**Issue by farski** [PRX/metrics.prx.org#145]
When the interval and preset quick select menus become visible they do they weird little expand animation, but (on Chrome, at least) just of the padding around the contents. The advanced selector menu only seems to do it after the firs time that it's become visible.

**Comment by pkarman** [comment]
@sandikbarr can you duplicate this and give some guess as to estimate? I'm giving it a medium priority.

**Comment by sandikbarr** [comment]
can do. I actually already found a typo in the transition and have this fixed in my current PR.
