### ISSUE TITLE
Scrunched hit zone for menubar items

### ISSUE THREAD

**Issue by farski** [PRX/metrics.prx.org#146]
I would expect the entire zone within the border to be clickable for these menu bar widgets

![image](https://user-images.githubusercontent.com/3483/34742745-386ed3a6-f555-11e7-9452-35733a4af181.png)

but the highlighted area around the edge is not active

![image](https://user-images.githubusercontent.com/3483/34742739-30b7ba06-f555-11e7-81fc-55c0d9373e29.png)

**Comment by pkarman** [comment]
@sandikbarr can you duplicate and estimate please?

**Comment by sandikbarr** [comment]
I'm grouping some changes to the dropdowns together and will have this fix included as well.

**Comment by sandikbarr** [comment]
I lied. This problem is bigger than the dropdowns. Icon buttons have margin on them that padding can't seem to take the place of. I could make the margin clickable but that doesn't change the color of the icon on hover. I'm going to pull this back out of the sprint and into the backlog.
