### ISSUE TITLE
X axis labels can get truncated

### ISSUE THREAD

**Issue by farski** [PRX/metrics.prx.org#147]
In some cases when a label near the right extreme of the axis is drawn it can get cut off

![image](https://user-images.githubusercontent.com/3483/34742897-db764700-f555-11e7-8a52-b8cd0d44b24a.png)

**Comment by pkarman** [comment]
@farski what's the desired behavior? My suspicion is that this is an issue with the charting library, and the alternative would be something like wrap rather than truncation, which might be worse.

**Comment by sandikbarr** [comment]
Looks like the recommended solution is to add padding in the chart config. https://github.com/c3js/c3/issues/219 Sounds like they did add a fix for this at one point, but it doesn't seem to work with our date labels. It's worth a shot, but there's definitely more than one complaint about this, so can we time box an attempt to address this issue by adding padding to the chart config?

**Comment by farski** [comment]
That seems like a good approach

**Comment by pkarman** [comment]
@sandikbarr let's spend an hour max on this and bump out of beta if padding does not fix.

**Comment by sandikbarr** [comment]
fixed! forever! adding to the sprint...
<img width="878" alt="screen shot 2018-02-01 at 4 52 07 pm" src="https://user-images.githubusercontent.com/2250413/35707665-4d35ba20-0770-11e8-834f-dce56cd16919.png">
