### ISSUE TITLE
stop rounding date ranges to interval

### ISSUE THREAD

**Issue by sandikbarr** [PRX/metrics.prx.org#150]
Castle will be updated to support partial weeks and months in the rollups. https://github.com/PRX/castle.prx.org/issues/47 Change the front end to stop rounding off the date ranges to the beginning and end of the week or month.

**Comment by pkarman** [comment]
marked this "high" to keep it in beta.

**Comment by cavis** [comment]
going to wait on this, until @sandikbarr's upcoming make-downloads-an-effect change hits.
