### ISSUE TITLE
untoggling everything displays no chart

### ISSUE THREAD

**Issue by sandikbarr** [PRX/metrics.prx.org#154]
Tried to add a placeholder in the event that the user untoggled all the chart options, but I struggled with it because of the loading status limitations. Should look at adding loading status on metrics stores first then putting in a placeholder in that area.

**Comment by farski** [comment]
Is it possible for the checkboxes to retain their color, even when in the unchecked state? If we could do that, when nothing is explicitly selected we could have the chart display the default selection anyway (ie, if nothing is explicitly selected, we implicitly select the first five items in the table).

Something along these lines maybe
![image](https://user-images.githubusercontent.com/3483/35161824-5bef4b6e-fd0f-11e7-9c0e-303dd39b24d4.png)

**Comment by sandikbarr** [comment]
I thought about always default displaying some data in the chart as well. I worried that may be frustrating if someone was trying to toggle off everything then toggle on the one they want to see.

**Comment by sandikbarr** [comment]
I was thinking more along the lines of a placeholder "You have nothing selected." In order to implement that correctly, I need to add support for the metrics loading state.

**Comment by sandikbarr** [comment]
Placeholder IMO is least surprise

**Comment by farski** [comment]
I've been trying to come up with a good solution to the "I have a lot of things selected and now I only want one thing selected" scenario.

Closest I've gotten is a button that appears on hover that allows you to select only that episode,

![image](https://user-images.githubusercontent.com/3483/35162397-36784262-fd11-11e7-8dd2-afb10a210c3d.png)

**Comment by sandikbarr** [comment]
I thought about the select all/select none toggle then selecting only a single checkbox that I felt like you'd often see in multiple checkbox scenarios, but that doesn't quite feel right without an extra step to apply, and I don't think we want that here either.

**Comment by sandikbarr** [comment]
We may also want to step back and consider that this episode selection may not be quite the right solution. I know @gcampo88 and @cavis weren't quite feeling it when they did reviews on it when it was new and we hadn't really talked about the plans for it outside the episode selection design meeting that they weren't in on.

I had some thoughts that maybe the user could choose the page size (from 5, 10, 15, up to 20 episodes) and all the episodes are toggled on by default. This would allow users to take a look at episodes together that cross our current page boundaries.

**Comment by pkarman** [comment]
This ticket feels like it has multiple issues in it. Is the "no thing selected" vs "how do I select one thing" really the same issue? Can we split into multiple tickets?

**Comment by sandikbarr** [comment]
Agreed. Here is a separate ticket for selecting a single episode: https://github.com/PRX/metrics.prx.org/issues/177

We don't have a resolution on "no thing selected" so let's resolve that here.
