### ISSUE TITLE
Calendar UI shifts when number of weeks change

### ISSUE THREAD

**Issue by farski** [PRX/metrics.prx.org#156]
![ezgif-4-c7efc9ea1a](https://user-images.githubusercontent.com/3483/34839529-e2747326-f6cf-11e7-8514-9a7f7f259540.gif)

**Comment by pkarman** [comment]
@sandikbarr can you duplicate and estimate please?

**Comment by sandikbarr** [comment]
This is a flex align issue that I thought I handled when I first implemented it. Oops, guess I didn't.
