### ISSUE TITLE
Range separator shouldn't be a hyphen

### ISSUE THREAD

**Issue by farski** [PRX/metrics.prx.org#158]
![screen shot 2018-01-12 at 9 51 02 am](https://user-images.githubusercontent.com/3483/34880323-1e91475e-f77e-11e7-9a88-6a3df8c204c6.png)

en-dash
![image](https://user-images.githubusercontent.com/3483/34880395-4baf6d88-f77e-11e7-946b-5d4589422ff0.png)

horizontal bar
![image](https://user-images.githubusercontent.com/3483/34880419-5d2bd86c-f77e-11e7-861b-6706f823212a.png)

em-dash
![image](https://user-images.githubusercontent.com/3483/34880433-68c4d958-f77e-11e7-99d9-250415fed2ad.png)

**Comment by farski** [comment]
I would pick horizontal bar

**Comment by sandikbarr** [comment]
So you want `&horbar;`?

**Comment by farski** [comment]
Yeah that works. I think it's safe to just use the character without the escaped entity, but either way, that's the one I prefer of those options.

**Comment by pkarman** [comment]
@sandikbarr iirc this is fixed in a pending PR?

**Comment by sandikbarr** [comment]
nope, not this one. I would have if I were touching that code, but I didn't.

**Comment by pkarman** [comment]
https://www.compart.com/en/unicode/U+2015

used hex entity for clarity since some text editors may balk at higher utf-8 codepoints.
