### ISSUE TITLE
Slight layout shift with summary table expand

### ISSUE THREAD

**Issue by sandikbarr** [PRX/metrics.prx.org#161]
When I added the sidebar nav, I noticed I was getting a slight layout shift in the size of the table when expanding the summary table.

**Comment by pkarman** [comment]
@sandikbarr can we timebox to an hour and bump out of beta otherwise?

**Comment by sandikbarr** [comment]
I did already spend an hour on this when I merged in the summary table changes TBH, which is why I ended up opening this ticket. I think we need to consider the new table tickets https://github.com/PRX/metrics.prx.org/issues/175, https://github.com/PRX/metrics.prx.org/issues/173,  and what may change with the table before or after beta before spending much more time on this.

**Comment by sandikbarr** [comment]
no longer an issue
