### ISSUE TITLE
Improve design of paging control

### ISSUE THREAD

**Issue by farski** [PRX/metrics.prx.org#162]
![image](https://user-images.githubusercontent.com/3483/35049162-19a93f6a-fb6d-11e7-8511-469a0d2bf782.png)

This could use a more polished final design

**Comment by kookster** [comment]
that sounds like you're volunteering to provide some polish, maybe? ;)

**Comment by pkarman** [comment]
@farski I am assigning to you for design work. Please add an Estimate so we can get this in the next sprint.

**Comment by pkarman** [comment]
Actually this is a duplicate of https://github.com/prx/styleguide.prx.org/issues/83 which is already groomed. Closing this and assigning that one to @farski
