### ISSUE TITLE
Hard to tell which page is active

### ISSUE THREAD

**Issue by farski** [PRX/metrics.prx.org#163]
![image](https://user-images.githubusercontent.com/3483/35049184-2ee57a6a-fb6d-11e7-98df-4a3bd7935a8a.png)

Likely this will get covered by #162 but in the interim might be good to add some contrast

**Comment by sandikbarr** [comment]
Duplicate of https://github.com/PRX/styleguide.prx.org/issues/83

**Comment by pkarman** [comment]
closing as dupe
