### ISSUE TITLE
responsive sidebar nav

### ISSUE THREAD

**Issue by sandikbarr** [PRX/metrics.prx.org#171]
implement #130 
[Mobile.pdf](https://github.com/PRX/metrics.prx.org/files/2051084/Mobile.pdf)

* [ ] The sidebar/subnav menu will have a list of top level navigation items with subnavigation menus that expand and collapse with navigation.
* [ ] Top level nav items will have an icon and button text shown @farski do you have specific assets for those icons?)
* [ ] Navigation items are `#1a1a1a` black and `#0089BD` blue when active active.
* [ ] When screen size (or responsive to window size?) is below ____, the menu will reduce to a submenu collapsed below the header, and the currently active item will be shown as the submenu heading.
* [ ] The menu items are Performance (is this episode comparison by release date? and are we adding it as a COMING SOON item?), Reach (is this the new Downloads?), Demographics (geo), and Devices (user agents)

Question: where has the podcast today and last 7 days and most recent episode info gone? Is that  under "Performance"? to be displayed in the content area? is this moving to more of a dashboard?
![screen shot 2018-06-06 at 10 28 46 am](https://user-images.githubusercontent.com/2250413/41048590-ad3f64dc-6974-11e8-802a-5ab81f1310ba.png)

**Comment by sandikbarr** [comment]
Also address responsive footer social icons get crowded to the columns of links.

**Comment by farski** [comment]
Icons: 

- [Gauge](https://thenounproject.com/search/?q=speedometer&i=145001)
- [Globe](https://thenounproject.com/search/?q=earth&i=407361)
- [Headphones](https://thenounproject.com/search/?q=headphones&i=1388318)
- [Smartphone](https://thenounproject.com/search/?q=smartphone&i=1012798)
