### ISSUE TITLE
Not obvious that interval data can scroll

### ISSUE THREAD

**Issue by farski** [PRX/metrics.prx.org#172]
Once the interval data is enabled for the table (ie "Show more") it's not immediately apparent that that section of the table can scroll to reveal the rest of the range in cases where scrollbars are not always visible

![image](https://user-images.githubusercontent.com/3483/35161552-929cae64-fd0e-11e7-8fd6-33966a22813a.png)

**Comment by sandikbarr** [comment]
Given that macs hide scrollbars when not in use, do you want to provide some design guidance on this one, @farski?

**Comment by farski** [comment]
The working plan is to take detailed interval data out of the main page table, and make it available at least as an downloadable export or in some other way on the page, which avoids this problem.
