### ISSUE TITLE
Table doesn't expand to fill all available space

### ISSUE THREAD

**Issue by farski** [PRX/metrics.prx.org#175]
![image](https://user-images.githubusercontent.com/3483/35162545-b91468b8-fd11-11e7-8cbf-b916b3e50249.png)

**Comment by sandikbarr** [comment]
@farski did you mention there was some design work being done on this during Bernard? Will that be ready for Clarissa?

**Comment by farski** [comment]
The working plan is to take detailed interval data out of the main page table, and make it available at least as an downloadable export or in some other way on the page, which avoids this problem. Without the number of columns changing in the table dynamically, and with the whole page going responsive, the table should expand to fill all the available width of the page./
