### ISSUE TITLE
Promotion/links on existing sites

### ISSUE THREAD

**Issue by pkarman** [PRX/metrics.prx.org#182]
Should we link to the metrics app from publish, e.g.?

**Comment by pkarman** [comment]
@sandikbarr @cavis iirc we can link directly to a specific series, yes? Could we add a link to the relevant metrics URL from the series profile page in publish.prx.org?

**Comment by pkarman** [comment]
If we do this, should include description/screenshot in #179 / #180

**Comment by sandikbarr** [comment]
Yes, we can direct link to both a series or an episode (or set of episodes) in metrics from Publish. Currently in Publish on the story page we have a metrics tab that we may want to consider replacing with a link. Linking to a series probably is more useful, just stating what we've got over there.

**Comment by cavis** [comment]
I'm going to PR an update to the Publish metrics tab.

**Comment by sandikbarr** [comment]
Nice. I was just about to bring this up in the channel actually. Should we also link to the series from series routes?

**Comment by cavis** [comment]
I'm not entirely sure where a link would go, on the Series page.  Would make more sense if we had some very basic castle numbers in the left-column, and could put the link there.  Opened another ticket to rethink how we show/link metrics -> PRX/publish.prx.org#504

**Comment by pkarman** [comment]
before:
![screen shot 2018-02-22 at 1 54 02 pm](https://user-images.githubusercontent.com/1205061/36561040-3181896c-17d8-11e8-9c91-cb90cc75fe96.png)

**Comment by pkarman** [comment]
after:
![screen shot 2018-02-22 at 2 02 29 pm](https://user-images.githubusercontent.com/1205061/36561333-10569ba0-17d9-11e8-9fcb-8debf20a7ba6.png)
