### ISSUE TITLE
Paging quickly causes an error

### ISSUE THREAD

**Issue by farski** [PRX/metrics.prx.org#185]
Not 100% sure it's because of the speed, but I can't make the error show up when I wait a long time between paging actions

https://slack-files.com/T0256R4CK-F8Y18GH7S-9f88368518

**Comment by sandikbarr** [comment]
I am pretty sure I fixed this. Ran into a similar error and added a filter to building the episode table data to prevent the error. https://github.com/PRX/metrics.prx.org/blob/master/src/app/downloads/downloads-chart.component.ts#L114

**Comment by pkarman** [comment]
@farski can you verify whether this is still an issue?
