### ISSUE TITLE
Some goofiness with video episodes

### ISSUE THREAD

**Issue by farski** [PRX/metrics.prx.org#194]
I _think_ both of these are probably because it's a video, can't be certain, though.

Some columns get 0's, but all-time does not:
![image](https://user-images.githubusercontent.com/3483/35739506-cbf4ceb6-07ff-11e8-8dd5-7bb2bbf0d35b.png)

Outputs an error:
![image](https://user-images.githubusercontent.com/3483/35739519-d6600910-07ff-11e8-81b8-0e61907410d0.png)

(Found on 99pi: https://metrics.prx.org/37983/downloads/episodes/monthly;page=1;standardRange=Last%20month;beginDate=Mon,%2001%20Jan%202018%2000:00:00%20GMT;endDate=Wed,%2031%20Jan%202018%2023:59:59%20GMT;chartPodcast=true;episodes=229306,229435,229558,229558,229435,229306,229898,229057,228391,225998,225266)

**Comment by farski** [comment]
Actually that error shows up twice for Dog Talk, which has no video episodes
![image](https://user-images.githubusercontent.com/3483/35739592-0f967318-0800-11e8-9b08-392ff97aa10a.png)

Though it does have one episode which is an MP4 rather than an MP3. But only one afaik.

**Comment by cavis** [comment]
Any episode with 0-total-downloads will show that error.  (It's a 404 from Castle).  We should catch these, and display them as 0s on the table.

We currently don't count video downloads at all - thus they're always going to have the error.
