### ISSUE TITLE
Unknown error on initial load

### ISSUE THREAD

**Issue by pkarman** [PRX/metrics.prx.org#198]
![screen shot 2018-02-05 at 10 30 53 am](https://user-images.githubusercontent.com/1205061/35816278-f11d1948-0a5f-11e8-87f1-d63b02dc2a59.png)

![screen shot 2018-02-05 at 10 31 02 am](https://user-images.githubusercontent.com/1205061/35816290-f7c90efa-0a5f-11e8-9633-113e5c3f2c2c.png)

![screen shot 2018-02-05 at 10 31 21 am](https://user-images.githubusercontent.com/1205061/35816337-0e9d73aa-0a60-11e8-8f8a-b533803e63cc.png)

**Comment by cavis** [comment]
You probably have a series with 0 stories, in the top-level series dropdown.  (Thus it has no `prx:stories` rel).  We should be checking for that!

**Comment by palomao** [comment]
related: I received this error when clicking through 2nd page for TED.
![screen shot 2018-02-05 at 11 36 38 am](https://user-images.githubusercontent.com/17989422/35816600-16c91440-0a69-11e8-8ab6-e367ab938ac7.png)

**Comment by pkarman** [comment]
The top-level dropdown for me has only one choice: Radiotopia.

**Comment by sandikbarr** [comment]
Pretty sure I know what the Unknown error is when first loading the app before it has navigated to having the seriesId in the url. It's trying to load episodes before it has the series id. Can fix.

Errors with GUIDs in the error text are legitimate non 404 errors from Castle.

**Comment by pkarman** [comment]
@sandikbarr could we change the error message for legit 404 errors so that they are "known" rather than "unknown"? Maybe instead:

> No episode metrics available for {guid}

**Comment by sandikbarr** [comment]
Sorry if I was unclear. @cavis did a fix with 404s last week that translates them into zeroes. We were seeing 404s where Castle had no record of the episode, so 0 listens. The "Unknown" errors are going to be legit errors often from the server, such as occasional 500s we've seen from Castle, or coding errors for things like this particular issue that failed before actually making a network request, so no error code on it.

**Comment by sandikbarr** [comment]
^^ @pkarman so I think this one from above is a non 404 Castle error. I saw that Ryan's 404 => 0 listens fix is deployed and working.
<img width="630" alt="screen shot 2018-02-05 at 1 42 43 pm" src="https://user-images.githubusercontent.com/2250413/35825121-7c3a5b34-0a7a-11e8-97f5-40cbac85dc7d.png">

**Comment by pkarman** [comment]
thanks for clarifying @sandikbarr - closing this then.
