### ISSUE TITLE
Add app to CICD

### ISSUE THREAD

**Issue by kookster** [PRX/metrics.prx.org#2]

**Comment by sandikbarr** [comment]
Planning to work with @ryan on this, may want to budget some time during the sprint. I think we can start on this at any time, no dependencies with ongoing metrics tasks.

**Comment by cavis** [comment]
Intended more for existing apps ... but this could be somewhat useful -
 https://github.com/PRX/internal/blob/master/guides/prxci_migration.md

**Comment by sandikbarr** [comment]
blocked in PR + need a production AUTH_CLIENT_ID for secrets
