### ISSUE TITLE
meaning of "All Episodes" checkbox ambiguous

### ISSUE THREAD

**Issue by gcampo88** [PRX/metrics.prx.org#200]
Seems like a "select all" checkbox that would then tick every other episode's checkbox 
![image](https://user-images.githubusercontent.com/16007382/35816496-da331b5c-0a68-11e8-9bca-374cb427d0b1.png)

**Comment by pkarman** [comment]
+1 that's the UX pattern I've seen in gmail etc.

**Comment by sandikbarr** [comment]
Tagging @farski for design input
