### ISSUE TITLE
Should clear out page info when navigating to different podcast?

### ISSUE THREAD

**Issue by gcampo88** [PRX/metrics.prx.org#202]
Currently if you navigate from one show to another, paging + timeframe + interval info is retained as you go to the new podcast. Feels like it would be better at least to wipe out the page info, so your view of the new show isn't page 9 or whatever on first look. 

** especially bad if there is no page X on the podcast you navigate to --  you get no chart and a one-line table, looks like a mistake.

**Comment by pkarman** [comment]
+1 can reproduce.

Managing state is a Really Hard problem. Seems like a few tickets opened around this UX. I expect we'll need to iterate a few times.
