### ISSUE TITLE
No episodes selected, graph disappears

### ISSUE THREAD

**Issue by pkarman** [PRX/metrics.prx.org#203]
When I click the "Most Recent" episode in the left menu, I get the "Episodes" graph type automatically. If I de-select the one selected Episode, the graph completely disappears. It wasn't clear to me for several seconds what exactly had happened - felt broken.

I wonder if, since the chart type automatically switches based on selecting an episode, when no episodes are selected, the chart type should switch automatically to the "Podcast" type so that the graph never disappears entirely. I.e., goes back to the default from initial page load. That would feel more intuitive to me.

**Comment by sandikbarr** [comment]
My intention was to just put in a placeholder stating that you don't have any data selected, but it sounds like that's not what is desired. Conversation about auto selecting episodes when all have been unselected is here: https://github.com/PRX/metrics.prx.org/issues/154

**Comment by pkarman** [comment]
A placeholder would be ok too, maybe with a link to the podcast graph? Thanks for the xref link. I will close this since #154 is still open.
