### ISSUE TITLE
Navigating to page 1 should reset to default episode selection

### ISSUE THREAD

**Issue by gcampo88** [PRX/metrics.prx.org#204]
If you have ever clicked on the "most recent" link in the podcast profile, then when you are on page 1 of the table, only that one episode will be charted. It's strange to navigate to other table pages and have the default 5 shown, then come back to page 1 and have only the one episode shown. Seems like it'd be better to restore the default 5 when navigating to page 1.

**Comment by pkarman** [comment]
Related to #206 ?
