### ISSUE TITLE
Strange episode selection behavior

### ISSUE THREAD

**Issue by farski** [PRX/metrics.prx.org#206]
Steps to reproduce:

1. Load Showcase metrics
1. Select _Secrets #4_ from Most Recent in profile
1. Turn on _Secrets #1_ in table
1. Turn off _#4_ in table
1. Turn off _#1_ in table
1. Turn on #4 in table

Only one thing should be selected at this point, but _#1_ and _#4_ will be

**Comment by pkarman** [comment]
I can reproduce.

**Comment by farski** [comment]
Also seems to happen any time it goes from 0-selected-episodes to 1 selected episode, and the selected episode isn't the episode that was selected prior to no episodes being selected

(🤔  I think that made sense)
