### ISSUE TITLE
Whichever number of shows you select on the first page are automatically selected for the 2nd, 3rd, etc...pages

### ISSUE THREAD

**Issue by palomao** [PRX/metrics.prx.org#207]
![screen shot 2018-02-05 at 11 43 56 am](https://user-images.githubusercontent.com/17989422/35816991-1ff97e8c-0a6a-11e8-8bda-2e97f50a4f34.png)
![screen shot 2018-02-05 at 11 44 01 am](https://user-images.githubusercontent.com/17989422/35816995-23538424-0a6a-11e8-9031-e0f6bb0ae036.png)

**Comment by pkarman** [comment]
maybe related to #202?

**Comment by gcampo88** [comment]
Actually I think this is the decided-upon default selection of top 5 rows of table for any new page you navigate to. Has been controversial in reviews, I think at least two of us have called it out as odd, but it's deliberate as of now.

**Comment by sandikbarr** [comment]
We are definitely not where we should be with the episode selection UX.

My thoughts on a possible adjustment for this odd behavior without taking any large swings at it is to default select all checkboxes, starting with a page size of 5, and also add the ability for the user to change the page size. We're trying to prevent too many requests to Castle at once (the reasonable limit/page size of selected episodes is 20) as well as deal with the problem that collecting a full list of episodes is a little slow (although it has improved significantly by hitting the public url.) We do want to allow the ability for users to chart different episodes together, but with this chart style of dates on the x axis, the usefulness of charting episodes together is limited by how far apart their release dates are. Adding the ability to increase the page size would allow users with shorter release cycles to chart more/different episodes together.

I do think it would be better if the behavior were having all checked by default even if the default page size were smaller and the user were toggling off display.

**Comment by sandikbarr** [comment]
We will start by keeping the page size at 10 and chart all episodes by default. 👍 Small change.
