### ISSUE TITLE
Frequently getting unknown errors

### ISSUE THREAD

**Issue by farski** [PRX/metrics.prx.org#208]
Don't have steps to reproduce this yet, but I'm seeing it very regularly

![image](https://user-images.githubusercontent.com/3483/35817020-32ea3f7c-0a6a-11e8-98d3-c0f855c6bc59.png)

**Comment by pkarman** [comment]
related to #198

**Comment by pkarman** [comment]
@farski can you confirm if this is still an issue for you? The fix for #198 should be in prod now.

**Comment by farski** [comment]
Haven't seen this in a while. Will reopen if it pops back up
