### ISSUE TITLE
Checkboxes slooooow when viewing 365 days

### ISSUE THREAD

**Issue by cavis** [PRX/metrics.prx.org#209]
When viewing 365 days of daily data, chart starts to lag quite a bit.

Doesn't happen if i start with a page reload on the "weekly" or "monthly" intervals.  But once i have loaded daily data, things tend to stay slow forever.

**Comment by cavis** [comment]
This can also happen when loading 30 days of hourly data.

I'm also noting that it's not just checkboxes lagging - it's the whole UI.  Must be some change detection leak, running on every datapoint all the time.  (Perhaps some date-math being executed too often - not just when the source data updates).

**Comment by cavis** [comment]
Yeah, on my machine, the interface becomes basically unusable at 30-days-hourly.

**Comment by sandikbarr** [comment]
to be used to evaluate chart solution
