### ISSUE TITLE
Data doesn't populate in Today or 7 Day section

### ISSUE THREAD

**Issue by palomao** [PRX/metrics.prx.org#210]
![screen shot 2018-02-05 at 11 48 12 am](https://user-images.githubusercontent.com/17989422/35817116-83f060b8-0a6a-11e8-8179-cd454f8088a1.png)

**Comment by sandikbarr** [comment]
We pulled this stuff from the Beta release, should maybe reconsider https://github.com/PRX/metrics.prx.org/issues/144

**Comment by pkarman** [comment]
yeah, I'd be inclined to hide these elements in the UI since we bumped out the functionality of #144

**Comment by sandikbarr** [comment]
closed as dup of #144 to implement
