### ISSUE TITLE
Graph blink on load

### ISSUE THREAD

**Issue by pkarman** [PRX/metrics.prx.org#211]
Whenever the graph is rendered, it pauses for a second, blinks and re-renders.

**Comment by cavis** [comment]
+1!

![image](http://cav.is/i/bd2x7.gif)

**Comment by sandikbarr** [comment]
This one and #219 and #230 make me think we should look into using the onrendered chart callback and add it to the loading state to display a spinner.

**Comment by sandikbarr** [comment]
to be used to evaluate chart solution
