### ISSUE TITLE
Active chart type should be more distinct

### ISSUE THREAD

**Issue by gcampo88** [PRX/metrics.prx.org#212]
Hard to tell right now which one you're on 
![image](https://user-images.githubusercontent.com/16007382/35817207-c0f49290-0a6a-11e8-91aa-49ec012151c2.png)

**Comment by pkarman** [comment]
+1 maybe outline in color?

**Comment by sandikbarr** [comment]
@farski thoughts? would this be a good use of color? Seems like it would also be nice for these buttons to have a :hover and :focus interaction. Perhaps like the new paging buttons, highlight grey on hover and background color blue with white chart lines on active?
