### ISSUE TITLE
Sometimes menus get cut off

### ISSUE THREAD

**Issue by farski** [PRX/metrics.prx.org#215]
Seems like maybe by the chart?

![image](https://user-images.githubusercontent.com/3483/35817523-a5936cbe-0a6b-11e8-955d-9bad9913f1e1.png)

**Comment by sandikbarr** [comment]
The css animation is waiting on the browser to finish whatever else it's doing. In order to resolve this, I expect that we would remove the animation.

**Comment by sandikbarr** [comment]
Along with #219, #230, and #211 another solution to this may be to show the loading indicator when the chart is building. This would prevent the user from clicking into menus until the chart is finished (which I believe is the "whatever else it's doing" that is preventing the css animation.)

**Comment by sandikbarr** [comment]
to be used to evaluate chart solution
