### ISSUE TITLE
Range vs Period

### ISSUE THREAD

**Issue by farski** [PRX/metrics.prx.org#217]
![image](https://user-images.githubusercontent.com/3483/35817561-bf4db236-0a6b-11e8-873f-502074ed5775.png)

![image](https://user-images.githubusercontent.com/3483/35817564-c24f6970-0a6b-11e8-9dce-8a579cee562a.png)

I believe these always refer to the same thing, so it may make sense to use a single term consistently.

**Comment by pkarman** [comment]
+1 for consistent labeling
