### ISSUE TITLE
Checkbox UX lag

### ISSUE THREAD

**Issue by cavis** [PRX/metrics.prx.org#219]
When clicking checkboxes, the response is just a bit too slow for my taste.  I think it's waiting for the chart to update, before updating its own checked-state.

I want smoother/quicker feedback, to inspire confidence in my click choices.

![image](http://cav.is/i/12g4q.gif)

**Comment by sandikbarr** [comment]
This one and #211 and #230 make me think we should look into using the onrendered chart callback and add it to the loading state to display a spinner.

**Comment by sandikbarr** [comment]
to be used to evaluate chart solution
