### ISSUE TITLE
paging menu should shift left when you're 10 in

### ISSUE THREAD

**Issue by gcampo88** [PRX/metrics.prx.org#222]
If I want to get to page 18 now I have to do it by clicking the right arrow 8x. Would be better here to have something like `6 7 8 9 *10* 11 12 13 14 15 of 31` so you can still jump several pages at a time 

![image](https://user-images.githubusercontent.com/16007382/35817955-c917e6be-0a6c-11e8-8e21-b0dfd0675f16.png)

**Comment by pkarman** [comment]
+1 pager should center on the current page. I have implemented these pagers many times and happy to scrub in on this.

**Comment by pkarman** [comment]
Addressed in https://github.com/PRX/metrics.prx.org/pull/244
