### ISSUE TITLE
More space between graph and the "Show more" and paging links

### ISSUE THREAD

**Issue by kookster** [PRX/metrics.prx.org#223]
![image](https://user-images.githubusercontent.com/46439/35818050-01a1a060-0a6d-11e8-9484-646ad9fcbbe2.png)

Should we have more space between graph and the "Show more" and paging links?

This close, it looks like those might be controls for the graph instead of the data table below.

**Comment by pkarman** [comment]
+1

I'd vote for a proper "bar" of nav tools.

**Comment by pkarman** [comment]
Addressed in https://github.com/PRX/metrics.prx.org/pull/244
