### ISSUE TITLE
only one link has orange on hover

### ISSUE THREAD

**Issue by gcampo88** [PRX/metrics.prx.org#225]
The username / image is the only thing that highlights in orange on hover -- and it doesn't link to anything anyway. Odd. 

![image](https://user-images.githubusercontent.com/16007382/35818209-6cf7c0e2-0a6d-11e8-8761-e9b9e91cdf5e.png)

**Comment by sandikbarr** [comment]
Relevant: https://github.com/PRX/publish.prx.org/issues/201 It's the same nav user component.

**Comment by sandikbarr** [comment]
I got feedback on having other links or menu items highlight orange, and it was a no. Gonna close this as dup of the publish ticket that is for actually implementing the nav user component (which actually lives in the styleguide and is used in both projects.)
