### ISSUE TITLE
URL filling up with selected episodes

### ISSUE THREAD

**Issue by cavis** [PRX/metrics.prx.org#226]
Feature + bug.  As you navigate around (using the paging / podcast-dropdown), more and more episode ids end up in the URL.  Eventually I've got 100+ of `;episodes=1234,5678`.  Keeps track of your which-episode-selected-state ... but you may end up sharing a gigantic url that reflects more than the state of what's currently rendered.

I would expect the `;episodes=` to reset every time you (1) change podcasts or (2) change pages.

**Comment by gcampo88** [comment]
that would help w/ this too https://github.com/PRX/metrics.prx.org/issues/202

**Comment by sandikbarr** [comment]
The intention is to save the state of episode toggling from other pages you have visited. I think I'm the only one who had any strong opinions about that, sounds like the majority wants to clear it out for anything not in view.

**Comment by pkarman** [comment]
+1 to clearing state on page or podcast change.
