### ISSUE TITLE
Link to current time period does nothing

### ISSUE THREAD

**Issue by kookster** [PRX/metrics.prx.org#227]
When you select a time period, like "Last 365 Days", and then go to click it again after it is the current selection, clicking the link does nothing.

Seems like it should either be disabled to indicate it is the currently selected period (as opposed to looking like a clickable link)? Or some other behavior besides doing nothing when clicked - perhaps close the modal?

**Comment by sandikbarr** [comment]
It is indicated as active, but the contrast is so low it's hard to tell the difference. Since we haven't been able to solve this one https://github.com/PRX/styleguide.prx.org/issues/83, perhaps disabled would be better than active in this instance.
