### ISSUE TITLE
clicking Downloads again when you're already on it uncharts Podcast

### ISSUE THREAD

**Issue by gcampo88** [PRX/metrics.prx.org#228]
steps:
1) load a show and go to the Stacked Downloads view. 
2) click Downloads again in left nav. The podcast becomes uncharted, and everything after `/{interval}` in the URL goes away

**Comment by sandikbarr** [comment]
This got worse with the episode selection reset changes. Now it uncharts everything, but we have a helpful placeholder pointing to the Podcast chart. 🤓Bumping the priority to get this fixed sooner.
