### ISSUE TITLE
Long pause, no loading indicator, when selecting profile latest episode link

### ISSUE THREAD

**Issue by kookster** [PRX/metrics.prx.org#230]
When I have a year of daily data loaded, and click on the title for the latest episode in the profile, the page does nothing at first, then eventually loads, but would be nice to have a loadinf indicator after clicking the link

**Comment by sandikbarr** [comment]
This one and #219 and #211 make me think we should look into using the onrendered chart callback and add it to the loading state to display a spinner.

**Comment by sandikbarr** [comment]
latest episode link to be removed, ice boxing

**Comment by sandikbarr** [comment]
link removed, #253 covers chart loading
