### ISSUE TITLE
Better trending indicators for podcast profile based on episode release

### ISSUE THREAD

**Issue by kookster** [PRX/metrics.prx.org#234]
https://prx.slack.com/archives/G1LPN7S5V/p1517948047000325

sandi.barr [3:14 PM]
Longer term planning wild idea: what if the comparison was on releases of episodes instead of today vs yesterday, and this week vs last week. What if it compared the first 24 hours and first week of last episode release to the latest one.

**Comment by sandikbarr** [comment]
Instead of using the thisWeek, previousWeek, today, yesterday values available on the summary data end point on a single episode for trends, the front end would need to query the full datasets for the first 7 days and first 24 hours for the last two episodes and total the values for comparison.

**Comment by sandikbarr** [comment]
From talking with Julie, the key metrics are 24 hour, 7 day, and 30 day cumulative numbers. The most recent episode 30 day cums are used to quote download metrics to sponsors.

**Comment by sandikbarr** [comment]
trends are being removed, ice boxing
