### ISSUE TITLE
Profile summary values get big

### ISSUE THREAD

**Issue by farski** [PRX/metrics.prx.org#247]
![image](https://user-images.githubusercontent.com/3483/36279547-6cd70f8c-1265-11e8-9ce9-79d63734ec99.png)

Thousand thousands is a bit confusing. Maybe 1.37M once the numbers are big enough?

**Comment by sandikbarr** [comment]
Did I notice @gcampo88 correcting "K" to "k" for thousands the other day? Looks like "M" can also mean thousands in accounting. https://english.stackexchange.com/questions/181917/mixing-use-of-k-for-thousands-and-mm-for-millions

**Comment by gcampo88** [comment]
ha, if I did it was not deliberate! (someone had posted "32" in slack and I amended it to "32k" since that's what they meant -- did not know whether K or k was appropriate!

**Comment by sandikbarr** [comment]
trends removed, ice boxing

**Comment by sandikbarr** [comment]
removed, closing
