### ISSUE TITLE
401 ajax response should trigger new login

### ISSUE THREAD

**Issue by pkarman** [PRX/metrics.prx.org#250]
If you click in a stale browser tab on the site, the authn session may have expired and trigger 401 responses from castle, etc. However, the frontend just spins.

Catch the 401 response, remember the current route, and redirect to login.

**Comment by cavis** [comment]
That's odd ... the auth tokens issued by ID should be expiring before your prx_session cookie.  So normally, you just ask ID for a new auth-token, and retry the request.  (This is [in styleguide](https://github.com/PRX/styleguide.prx.org/blob/master/src/lib/src/hal/remote/halremote.ts#L107)).

And if your ID session/cookie has expired, [the AuthGuard](https://github.com/PRX/styleguide.prx.org/blob/master/src/lib/src/guard/auth.guard.ts#L12) should be redirecting you back to login.

That was the plan, anyways.  Apparently it's getting hung up somewhere along the way!

**Comment by sandikbarr** [comment]
verified this has been fixed by watching it happen
