### ISSUE TITLE
Average Cumulative Downloads

### ISSUE THREAD

**Issue by sandikbarr** [PRX/metrics.prx.org#251]
30 day cumulative downloads are used to quote download numbers to sponsors

**Comment by sandikbarr** [comment]
Bringing this back around. Specifically per Madeleine, is that we provide an average of this 30 day cumulative downloads number from the most recent 6 episodes. This number is a moving target, and Madeleine has to currently pull all this together manually. It would be super helpful to them, if we could show the average total from the charted/selected/most recent episodes along with each total in the number of days range. Additionally, we talked about the chart being more useful as cumulative numbers instead of interval based as we currently have in our downloads, but it's possible users want both options.

**Comment by brandonhundt** [comment]
@sandikbarr and @farski to follow up with Madeline.

**Comment by farski** [comment]
I've made a Quicksight dashboard that Madeleine seems happy with.
