### ISSUE TITLE
Geolocation table by country

### ISSUE THREAD

**Issue by sandikbarr** [PRX/metrics.prx.org#275]
* Table will show an unpaged list of unpaged list of all countries ordered by rank with the aggregate total for the date range (along with percent)
* Can countries be toggled on/off in the map/chart display via checkbox controls in the table?
* User can drill into individual countries to show data (and map/chart) by state/province/subdivision
* Can show either the full show or filter to a single episode

**Comment by farski** [comment]
Drill down (as a separate view) got really tricky to handle well on desktop and mobile without making the app feel a lot more complicated, so I think as long as we're doing just country and one level more granular than country, we can just do the drill down in the table. If we ever decide to add more granularity this probably won't work, but I think it's a good solution for the time being.

**Comment by farski** [comment]
When countries are toggled off, does that mean they no longer show up in the map?
