### ISSUE TITLE
Design review

### ISSUE THREAD

**Issue by farski** [PRX/metrics.prx.org#287]
I consolidated this into a single ticket until the review meeting on Monday

- Desktop sidebar needs some breathing room (more padding around elements, wider min width)
- There should still be a Downloads page that lives under the Reach heading (it will be the only page under reach for now) (auto select because it's a single subnav)
- Can we add a subtle hover state to the interval and date selector buttons - lightest grey, lighter than active chart type
- Mobile page nav should be 100% width
- Drop range rollup and chart type buttons on mobile
- ~~Date range presets should automatically apply on desktop~~
- Sidebar doesn't collapse at medium screen sizes
- Font adjustments (sidebar section headers, page title, picker buttons)

**Comment by pkarman** [comment]
Meeting scheduled for 7/5
