### ISSUE TITLE
Collapsing and auto-expanding sidebar at desktop and medium screen widths

### ISSUE THREAD

**Issue by farski** [PRX/metrics.prx.org#294]
Pulled out of #287

**Comment by sandikbarr** [comment]
In both desktop and tablet view, the side menu should slide out on hover. Previous designs just had this for a narrower window or tablet view, but it seems useful to conserve horizontal space on desktop as well.
![slide out menu](https://user-images.githubusercontent.com/2250413/50992291-51d84780-14dc-11e9-8f71-d80f54ac9ef4.png)
![slide out menu on hover](https://user-images.githubusercontent.com/2250413/50992292-51d84780-14dc-11e9-9513-dfcd6fbf2499.png)

**Comment by sandikbarr** [comment]
going with material sidebar instead
