### ISSUE TITLE
Monthly bar graph labels are dates

### ISSUE THREAD

**Issue by farski** [PRX/metrics.prx.org#307]
![image](https://user-images.githubusercontent.com/3483/45562016-220f8080-b817-11e8-936f-6d1be9c6a4b1.png)

A couple thoughts on how these labels currently appear: 

- The bars represent months, but the labels are individual days. I think it fairly obvious what that means, but would be clearer if the label were more explicit, e.g., _Sep. 2017_. There is the chance of confusion if someone thinks the label means _month ending on X date_
- Sometimes the label is not strictly the first day of the month that the bar represents (e.g., _Oct 31, 2017_ for the November 2017 bar, or _Mar 2, 2018_ for the March 2018 bar). That's pretty confusing and makes scanning the chart for a month difficult (a user is looking for October and sees the label with _Oct_, but is actually finding November)

**Comment by sandikbarr** [comment]
C3 sure makes odd choices. Used to be the monthly labels were month and year https://github.com/PRX/metrics.prx.org/commit/adf5a836fe773255ddc8f2cc546899702c5e46b2#diff-0445c8492e6c08ff66a15f1e7032b1f5, but that was changed with this date formats ticket https://github.com/PRX/metrics.prx.org/issues/83
