### ISSUE TITLE
"Other" series in graphs is always displayed

### ISSUE THREAD

**Issue by farski** [PRX/metrics.prx.org#311]
It looks like the _Other_ bar is being displayed in graphs, even when all series are included in the graph (eg. on the Form Factor page)

**Comment by sandikbarr** [comment]
<img width="654" alt="screen shot 2018-09-19 at 1 04 51 pm" src="https://user-images.githubusercontent.com/2250413/45772198-a80f3b00-bc0c-11e8-9f55-d13e65924881.png">
ha yeah totally a feature on the API, but I can remove it from the chart on the front end if the total is 0.
