### ISSUE TITLE
Changes to Downloads View (paging, selection)

### ISSUE THREAD

**Issue by IcusFMagni** [PRX/metrics.prx.org#350]

**Comment by sandikbarr** [comment]
Episode selection was added to paged downloads, but the episode selection menu is not shown in that view. This paged downloads/selected episode support was added to provide urls to episode data. I feel like episode selection and paged downloads don't mix well. There are two states for a given episode dataset, charted (with the checkbox toggle in the table below) and selected (through the route.) It's a bit awkward. It feels like instead episode selection should be applied to a drop date chart and paged downloads left alone.

**Comment by sandikbarr** [comment]
selecting downloads episodes through the route was separated out to resolve this
