### ISSUE TITLE
Geo grouped by date

### ISSUE THREAD

**Issue by farski** [PRX/metrics.prx.org#379]
via Kali:

>Since we turned off inventory tracking on 03/29/19 in Adzerk (running silent files on every pre 1/A1 and/or mid 1/A1 zone not filled by a paid ad) and Metrics doesn't export data by date, we can no longer easily and efficiently pull country and metro download data by date and by show. We use this for marketing requests to see the performance of outside campaigns they run (to increase traffic to our podcasts) and for some sales requests. There's a dropdown for daily/weekly/monthly breakout in Metrics, but it appears to only apply to the graphs at the top of the page. It would be ideal if this breakout choice could apply to the exportable CSV file as well. Thanks!

**Comment by sandikbarr** [comment]
I'm going to reach out to Kali on this one. It does export data by date, but only if you are not on a "totals" graph or map. The export changes when you select the line or stacked chart type.

**Comment by sandikbarr** [comment]
Yep, the exports on the interval charts were what Kali was looking for. Quality user feedback though that this wasn't at all obvious to figure out.
