### ISSUE TITLE
should episode release dates be in local timezone

### ISSUE THREAD

**Issue by sandikbarr** [PRX/metrics.prx.org#384]
Episode publish dates are displayed in UTC because everything else in metrics is UTC. It seems weird though.

**Comment by farski** [comment]
I'm still interested in exploring the concept of a show-level timezone attribute. Eg, the timezone setting for 99pi is US/Los Angeles, so no matter where you are when you're looking at that show times are in that timezone. Thinking mainly of teams that have folks in multiple TZ's, or people who are traveling around.

**Comment by sandikbarr** [comment]
cool. Is that a prerequisite or can we have the Publish and Metrics release dates match (browser local timezone) until we implement a show-level timezone preference?

**Comment by farski** [comment]
Just something that's crossed my mind as I've used the apps. I'll defer to @brandonhundt as to whether this is something we even want to consider, and how important it is.

**Comment by sandikbarr** [comment]
display release dates in local timezone for now until there is a per series timezone setting

**Comment by brandonhundt** [comment]
@sandikbarr Do we have a ticket for the per series timezone setting?

**Comment by sandikbarr** [comment]
no, would that go in https://github.com/PRX/publish.prx.org/issues probably?

**Comment by brandonhundt** [comment]
Probably, yes.
