### ISSUE TITLE
28 day performance chart

### ISSUE THREAD

**Issue by farski** [PRX/metrics.prx.org#387]

**Comment by farski** [comment]
This is an example from one of the Quicksight dashboards. It has episodes arranged by date (oldest to newest) along the X axis, only including episodes that were dropped > 28 days ago. Each bar is the 28 day total.

The lines are the 3-episode and 6-episode moving averages.

![image](https://user-images.githubusercontent.com/3483/57856399-f59f7000-77ba-11e9-9404-217a6952fdd8.png)

**Comment by farski** [comment]
Here's another example. Same bar graph, but instead of the lines directly graphing the averages, this shows the percent change of the 6-episode moving average. I.e., for the most recent episode, (the 6ep avg for the most recent episode - 6ep avg for the previous episode  / 6ep avg for the previous episode.

That metric I think it really handy to people that know what it's saying, but it's less obvious than the straight averages. The main quirk I've seen is that people will see a descending graph, and not quite get that it means the show is still, on average, growing, just at a slower rate.

![image](https://user-images.githubusercontent.com/3483/57856675-84ac8800-77bb-11e9-82df-410ba2a76bc7.png)

**Comment by farski** [comment]
This is the query for all the data behind those graphs 

```sql
WITH 
averaged_by_episode AS (
    SELECT 
        podcasts.id AS "Podcast ID",
        podcasts.title AS "Podcast Name",
        episodes.id AS "Episode ID", 
        episodes.title AS "Episode Title",
        concat(to_char(episodes.published_at :: DATE, 'yyyy-MM-dd'), ' ', episodes.title) AS "Dated Episode Title",
        episodes.published_at AS "Episode Drop Date",
        date_part('days', CURRENT_DATE - episodes.published_at) AS "Episode Age",
        -- Applies an index number to each episode. Smaller numbers are older, and 0 is the most recent (eg, -2, -1, 0)
        (1 - row_number() OVER (PARTITION BY podcasts.title ORDER BY episodes.published_at DESC)) AS "Recency Index",
        -- Total downloads for the episode (within the first 28 days of release)
        sum(count) AS "Downloads", 
        -- The 3-episode moving average (the average total downlodas of the previous two episodes and this episode)
        avg(sum(count)) OVER (PARTITION BY podcasts.title ORDER BY episodes.published_at ASC ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS "3 Episode Avg",
        -- The 6-episode moving average (the average total downlodas of the previous five episodes and this episode)
        avg(sum(count)) OVER (PARTITION BY podcasts.title ORDER BY episodes.published_at ASC ROWS BETWEEN 5 PRECEDING AND CURRENT ROW) AS "6 Episode Avg"
    FROM hourly_downloads
    JOIN episodes ON episodes.id = hourly_downloads.episode_id
    JOIN podcasts ON podcasts.id = hourly_downloads.podcast_id
    WHERE date_part('days', CURRENT_DATE - episodes.published_at) >= 28
        AND (hourly_downloads.dtim - episodes.published_at) <= INTERVAL '28 days'
    GROUP BY episodes.id, episodes.title, episodes.published_at, podcasts.title, podcasts.id), 
with_lags AS (
    SELECT 
        *, 
        -- Get the previous 3- and 6-episode averages for each episode
        lag("3 Episode Avg", 1) OVER (PARTITION BY "Podcast Name" ORDER BY "Episode Drop Date" ASC) AS "Previous 3 Episode Avg",
        lag("6 Episode Avg", 1) OVER (PARTITION BY "Podcast Name" ORDER BY "Episode Drop Date" ASC) AS "Previous 6 Episode Avg"
    FROM averaged_by_episode),
with_percent_change AS (
    SELECT 
        *,
        -- Calculate the change (as a percent) of each average
        (("3 Episode Avg" - "Previous 3 Episode Avg") / "Previous 3 Episode Avg") AS "3 Ep. % 𝚫",
        (("6 Episode Avg" - "Previous 6 Episode Avg") / "Previous 6 Episode Avg") AS "6 Ep. % 𝚫"
    FROM with_lags)
SELECT * FROM with_percent_change
ORDER BY "Podcast Name" ASC, "Episode Drop Date" ASC
```

**Comment by farski** [comment]
Questions: 

1. Time/effort needed for the first option (my sense is _minimal_, but want to confirm)
2. Does the %𝚫 version make enough sense to present, or what would we have to do to explain to users that it means (an info box with an explanation?)
3. If we include %𝚫 would it be feasible to add a toggle so that the user can switch between the raw values and the %𝚫?
4. Are Castle changes needed for any of this, or can the averages and percents get calculated on the frontend?

**Comment by sandikbarr** [comment]
* What are you doing with 28 day averages when an episode hasn't been out for 28 days? Is it still just a simple average of the available data?
* I don't have access to this Quicksight dashboard. Are those 28 day bars labeled in any way?
* Should this really be a view separate from the 28 day totals or should that horizontal graph of 28 day totals be evolved into this view? I don't see a lot of value in keeping both, feel like this is more additive than an entirely separate idea.
* I assume the averages and percents will be calculated on the front end as I've done with the cumulative data.

**Comment by farski** [comment]
• That query is only including episodes that were dropped > 28 days ago, so nothing that is incomplete should ever be factoring into an average.

• The bars are labeled with a `[Date] + [Title]` string. The date is in there only because there was no other way to get Quicksight to sort the episodes correctly
![image](https://user-images.githubusercontent.com/3483/57863555-4d90a380-77c8-11e9-8c19-cdc224b233a4.png)

• These feel like separate pages to me. Even though the data is related, functionally the are distinct enough that I think they each deserve their own page rather than just a view option of the same page. For example, I think having the episode selector makes a lot of sense on the drop day chart, but for the 28 day totals I think it should be highly opinionated and just always show all episodes in order (or the last X episodes). The bar chart on the drop day chart could just be replaced by this, I don't think we need both.

**Comment by farski** [comment]
Here's a mockup of how I'm thinking this could be implemented.

Pretty vanilla, but here are some key points:

- Independent Y axes; left for downloads, right for percent change
- I think it'd be fine for the initial release to show the most recent 50 episodes max (ie. no paging or other control to move through episodes, and no episode selection)
- The line graph is the 6-episode average percent change (as described above)
- The useful range of the right Y axis only really need to be ± 0.1 I think
- The table includes the `28 Day Total`, `3 Episode Avg`, `6 Episode Avg`, and `6 Ep. Avg % 𝚫`
- There doesn't need to be a total metric in the top left
- The only menu it needs is Export
- For cases where there are > 50 episodes for a show, the averages should take into account episodes that aren't being graphed
- If possible, the horizontal grid lines should follow the right Y axis, and ensure that there is a grid line at 0, and 0 should be centered vertically

Open to others' input on whether this should be called **28 Day Performance**, **28 Day Totals**, or something else

![image](https://user-images.githubusercontent.com/3483/58486948-d0a0ea80-8134-11e9-9afc-e76c1eff9991.png)

**Comment by brandonhundt** [comment]
@farski Overall nice work! I think the decision to base this off of insights dashboards is the right approach. Visually this works well and I understand what is happening intuitively. 

- If there is only one thing to export, does the export function need a dropdown or can it be a standalone button?
- 28 Day Performance is my vote, although any of your suggestions work. Don't overthink it :)

**Comment by farski** [comment]
@brandonhundt Export, I believe, usually has several options, so probably still a dropdown

**Comment by brandonhundt** [comment]
@farski Ok. This design and approach work for me.

**Comment by sandikbarr** [comment]
Export has CSV or Google Sheets options

**Comment by sandikbarr** [comment]
@farski does the `28 Day Performance` or `28 Day Totals` side menu item replace `Drop Day`? Do those interfaces go together under the same nav item? Currently, Drop Day allows for different options for how many days you're looking at, not always just 28 Days.

**Comment by sandikbarr** [comment]
I'm concerned about the performance of loading downloads data on all episodes on page load. It works with drop day where we start with 10 and users can manually select/load additional episodes. Can we limit this 28 day performance to a reasonable number of episodes back? Some shows have catalogs of hundreds of episodes.

**Comment by farski** [comment]
Above I suggested capping it at the most recent 50 in display, which would mean loading at most 55 (or 56?) episodes worth of data. Do you think that is too many?

Re: the nav, I didn't mean for the mockup to make a call on that. Separate views I assume would have separate nav items.

**Comment by sandikbarr** [comment]
Sorry for my misunderstanding, there's a lot of details here to sort through.

Yeah, I think 50 is probably too many, but we can try it.

**Comment by sandikbarr** [comment]
Can you explain a little more about the 28 Day Total/Averages for All Episodes from the mockup?

**Comment by farski** [comment]
I cannot, that was an oversight 😬 and should not exist
