### ISSUE TITLE
users need to be able to access urls with common parameters

### ISSUE THREAD

**Issue by sandikbarr** [PRX/metrics.prx.org#47]
Users should be able to access sets of parameters with a direct url. Given that the source of data is changing from CMS to Feeder, any podcasts or episode ids/guids in the url will be feeder based.

unresolved questions:
* Specific date ranges are not relevant over time, so do these go in the url? Maybe only when the date range is custom and does not match one of the canned options.
* Groups of episodes are also generally only relevant for a certain period of time. Do these go in the url?

(I'm estimating this at a 3 because I want to reserve some time to look at ngrx/router.)

**Comment by cavis** [comment]
I would vote for "everything" being in the URL.  Though that would require differentiating between absolute and relative date ranges first.  Is there any ticket to address that?

I seem to recall a screenshot from youtube, where you first get a dropdown full of relative ranges (last week, last month, etc), and then you can select "Custom date range" to get the timepickers to show up.

**Comment by sandikbarr** [comment]
* Since the intention of the google analytics event tracking is to see how users are using the custom and standard date range controls, I don't think we want to hide them right off the bat and influence their behavior.
* Maybe we'd want to keep the custom dates out of the url when a standard range is selected? But maybe not because that doesn't exactly work for looking at the same report the following day? But then if we have both custom and standard dates in the url, the url parameters aren't altogether valid the following day, so we have to sort that out anyway. What takes precedence, custom dates or standard range?

**Comment by pkarman** [comment]
Could we always put custom dates in the URL, and let the user decide whether they represent a floating/sliding range/window or not? Maybe a checkbox toggle indicating the dates are "hard" or "soft"?

**Comment by sandikbarr** [comment]
@pkarman feels like we're getting into build a report to export territory with that one, which I can see doing but I'd want to take a holistic approach on that and see what it means beyond the url
