### ISSUE TITLE
timepicker am/pm hours dont match 24hr chart/table times

### ISSUE THREAD

**Issue by sandikbarr** [PRX/metrics.prx.org#54]
The timepicker is using am/pm, but metrics chart and table show 24 hour clock times.

**Comment by kookster** [comment]
Hey @sandikbarr - I think I saw a recent discussion on slack about date formats, and the suggestion from @farski was it was ok to use different formats, as appropriate to the place in the app.

Is that the thinking on iceboxing this - we don't need to bring these into consistency right now?

**Comment by sandikbarr** [comment]
@kookster There are no longer any time pickers in the app, so I iceboxed it in case we decide to bring them back for hourly data.

**Comment by kookster** [comment]
well that's obvious once you say it! thanks for clarifying, my bad
