### ISSUE TITLE
Scheduled, not-yet-published episodes show up

### ISSUE THREAD

**Issue by gcampo88** [PRX/metrics.prx.org#75]
Should we be able to see scheduled episodes on metrics? Currently, if they're scheduled for future release, they show up. E.g. here, the top 3 episodes on the default view for Inflection Point are scheduled for future release (not sure why they have downloads... separate question)

![image](https://user-images.githubusercontent.com/16007382/32632415-89086fde-c571-11e7-81de-3661bf8cae4b.png)

app.component.ts filters episodes by publishedAt not null -- should it also check that publishedAt has passed?  
```typescript
      const episodes: EpisodeModel[] = docs
      // only include episodes with publish dates
        .filter(doc => doc['publishedAt']) // and published <= today?
        .map(doc => {...
```
going to leave this in "new" for confirmation of bug v. feature status

**Comment by sandikbarr** [comment]
not intentional, definitely seems like a bug. Need to check for published <= now in that filter.

I am not sure on the unpublished episode downloads though. I wonder if that one for 1/3/18 got into into a player somewhere or was published at one time?
