### ISSUE TITLE
Negative numbers

### ISSUE THREAD

**Issue by farski** [PRX/metrics.prx.org#79]
Ran across some negative numbers in the graph

![pasted image at 2017_11_21 09_15 am](https://user-images.githubusercontent.com/3483/33077362-a38856d2-ce9d-11e7-97ea-8689fcde8135.png)

**Comment by farski** [comment]
![pasted image at 2017_11_21 09_13 am](https://user-images.githubusercontent.com/3483/33077399-b9a6f932-ce9d-11e7-8be9-6fe07ae4b7bd.png)

**Comment by sandikbarr** [comment]
@farski can you verify if this is still occurring after the routing PR has now been been merged and deployed? If yes, please include steps to reproduce.

**Comment by farski** [comment]
Haven't seen this happen again
