### ISSUE TITLE
Include Apply button in design

### ISSUE THREAD

**Issue by sandikbarr** [PRX/metrics.prx.org#81]
Designs should include the apply button and answer the question, what does the button apply (just the dates? the interval? the chart type? episode selection?) There were some questions/suggestions about whether Apply could also function as a Refresh button in #78.

**Comment by pkarman** [comment]
this seems like a pretty critical UX element to decide on, since the new interactive bits are not all-of-a-piece as they were in the current layout. @farski do you have a sense on if you'll be able to get to this in this sprint?

**Comment by farski** [comment]
@pkarman this and https://github.com/PRX/metrics.prx.org/issues/80 should be done on Monday

**Comment by farski** [comment]
This is de facto covered by #80 at the moment the way I have things, so closing this for now
