### ISSUE TITLE
Date & time formatting

### ISSUE THREAD

**Issue by farski** [PRX/metrics.prx.org#83]
Across the app I think we should make sure that we avoid any ambiguous date formats (eg 10/11/12) in favor of something more verbose when space permits (eg Oct. 11, 2012) or an unambiguous short form when constrained (2012-10-11 or similar)

I would also favor using AM/PM for times, regardless of where we land on time zone support, rather than 24 hour time.

**Comment by sandikbarr** [comment]
What's left here is to update the styleguide to allow Input() of date format.

**Comment by sandikbarr** [comment]
This should get resolved with the implementation of the new date range picker https://github.com/PRX/styleguide.prx.org/issues/78. Although it is not clear to me whether or not we've decided to drop commas from the proposed date formats. https://github.com/PRX/metrics.prx.org/issues/80#issuecomment-351190601
