### ISSUE TITLE
Larger activation area for chart overlays

### ISSUE THREAD

**Issue by farski** [PRX/metrics.prx.org#87]
(For line/area graphs) Since there's really only one overlay per value on the x-axis (ie not one per data point), it could be nice to have the overlay track the cursor anywhere within the chart area, rather than just in close proximity to a point on a graph. [example](https://www.google.com/search?tbm=fin&ei=-mcdWtCeG4XI_QaCrbD4Aw&stick=H4sIAAAAAAAAAONgecRoyi3w8sc9YSmdSWtOXmNU4-IKzsgvd80rySypFJLgYoOy-KR4uLj0c_UNzKtyk8rSeADviEaCOgAAAA&q=NASDAQ%3A+AAPL&oq=AAPL&gs_l=finance-immersive.1.0.81l3.27218.27673.0.28442.5.5.0.0.0.0.97.320.4.4.0....0...1c.1.64.finance-immersive..1.4.318.0...0.94ZUElIomwA#scso=uid_Wh1oGAAK2JYK30jhWgXhfg_4:0)

**Comment by sandikbarr** [comment]
example link in description doesn't work for me

**Comment by farski** [comment]
https://www.google.com/finance If you click on pretty much any link in there you should see a graph that behaves this way

**Comment by farski** [comment]
This also behaves in a similar way: http://c3js.org/samples/simple_regions.html

**Comment by sandikbarr** [comment]
Weird, that C3 example doesn't do anything special with configuration in order to get that behavior. I tried that out quick by setting the chart type to line (the C3 default) and even with only one line and only 3 data points shown, the tooltip doesn't trigger until the cursor is pretty darn close to a point.

**Comment by farski** [comment]
This is probably my biggest frustrations with using the app at the moment. I know the work here is a bit of an unknown quantity since there's no obvious reason our charts are working differently than the examples, but I would like to reconsider the priority for Beta.

**Comment by sandikbarr** [comment]
@kookster can you weigh in on this? seems to be holding up beta, but I really can't see a way to change this in C3.

**Comment by sandikbarr** [comment]
to be used to evaluate chart solution
