### ISSUE TITLE
User Testing and Interview with producer

### ISSUE THREAD

**Issue by sandikbarr** [PRX/metrics.prx.org#9]
@farski and @sandikbarr will present their mockups to a producer (maybe Hrishi) for user testing. @pkarman and @sandikbarr are collaborating on user interview questions.

**Comment by pkarman** [comment]
questions posted in slack

**Comment by sandikbarr** [comment]
Scheduled for Friday at 3:30 ET with Jonathan Mitchell who is currently using Libsyn
