### ISSUE TITLE
Interactive range filter/selector on time series graphs

### ISSUE THREAD

**Issue by farski** [PRX/metrics.prx.org#90]
This has already been identified as low priority, just capturing in a ticket

[example](https://developers.google.com/chart/interactive/docs/gallery/controls#chartrangefilter)

**Comment by farski** [comment]
Looks like there's some rudimentary support possible using C3
http://c3js.org/samples/options_subchart.html

**Comment by sandikbarr** [comment]
to be used to evaluate chart solution
